### ISSUE TITLE
Busca de Produtos, podendo adicionar um ou mais itens ao carrinho

### ISSUE THREAD

**Issue by obrunopolo** [welington4tuna/RemedinVersao01#4]

**Comment by welington4tuna** [comment]
A página de busca recebe uma string através do NavParams. Está string é usada no método getMedicamento() que busca os produtos no banco de dados. No post para o servidor é enviado  um objeto { busca, bairro, cidade, lat, long }.
O retorno desse post é adicionado ao array listaMedicamento que será impresso no html.

Ps. add um provider só para a busca e encapsular as classes.
